- charts/hush-sensor/Chart.yaml
- charts/hush-sensor/templates/_helpers.tpl
- charts/hush-sensor/templates/daemonset.yaml
- charts/hush-sensor/templates/sensorconfigmap.yaml
- charts/hush-sensor/values.yaml
The ConfigMap allows customization of a subset of snoopy's configuration relevant
in Kubernetes, and passes to snoopy the actual namespace that it is deployed within.
> HUSH-269 Add snoopy's config map

- charts/hush-sensor/templates/daemonset.yaml
- charts/hush-sensor/values.yaml
Snoopy config volume must be readonly to prevent config overwrite. Therefore Location of sensor_uuid file and config.yaml should be different.
> HUSH-260 hush-sensor: templates/daemonset: Move snoopy-config to /opt/snoopy/config

- charts/hush-sensor/Chart.yaml
Bumping minor as we support ARM64 now so our DaemonSet's default
affinity has changed to allow arm64 as well.
> HUSH-260 hush-sensor: bump the version to 1.2.0

- charts/hush-sensor/values.yaml
We want to trace all pods in the upcoming friendly-customers release.
> HUSH-317 hush-sensor: change default pod tracing to "all-pods"

- .vscode/cspell.json
- charts/hush-sensor/templates/_helpers.tpl
- charts/hush-sensor/values.yaml
This PR adds support for `image.pullToken`.
Pull Token contains Container Registry credentials in a single string.
This improves user experience because a user needs to copy from UI only
a single string instead of 3 (username/password/registry).
> HUSH-323 Support image pull-token

- charts/hush-sensor/Chart.yaml
Releasing `image.pullToken` functionality.
> HUSH-323 bump the version to 1.4.0

- charts/hush-sensor/templates/_helpers.tpl
- tests/tests/test_kubeconform.py
shepherd has added unique token identifiers to deployment and image-pull
tokens. Check the identifiers so that tokens cannot be mistakenly
swapped in helm chart input.
> HUSH-346 hush-sensor: add check of token identifiers

- charts/hush-sensor/templates/daemonset.yaml
Was `/var/run/containerd` previously.
We want this to be equal to the path on the Host.
> HUSH-358 hush-sensor: map containerd directory to `/run/containerd`

- charts/hush-sensor/Chart.yaml
Versions are released frequently now while many times
breaking backward compatibility.
Use `v0` major version for this stage of development.
We will bump to `v1` for the MVP release.
> HUSH-366 hush-sensor: change the major version to `v0`

- charts/hush-sensor/templates/_helpers.tpl
- charts/hush-sensor/templates/daemonset.yaml
- charts/hush-sensor/templates/sensorconfigmap.yaml
- charts/hush-sensor/values.yaml
There are cases when snoopy cannot auto-detect CRI socket path.
Add support for specifying a custom path on the Host.
Map the directory of the path. This is done to allow snoopy
to reopen the socket in case it is recreated on the Host.
Pass the mounted CRI socket path to snoopy via configuration.
Allow specifying an extra set of volume mounts in sensor to allow containerd
socket directory be different from that of CRI socket.
> HUSH-358 hush-sensor: add support for custom `criSocketPath`

- charts/hush-sensor/Chart.yaml
- charts/hush-sensor/templates/_helpers.tpl
- charts/hush-sensor/templates/daemonset.yaml
- charts/hush-sensor/templates/deploymentsecret.yaml
- charts/hush-sensor/templates/sensorconfigmap.yaml
- charts/hush-sensor/values.yaml
- tests/tests/test_kubeconform.py
Deployment Token was split into two parts. The secret part is called
Deployment Password now.
Add support for Deployment Password as a separate input value and
as a pre-created Secret.
Store destructured Deployment Token into sensor config map.
> HUSH-361 Destructured deployment token

- .github/workflows/build.yaml
The matix build is not really used because we build on single OS only.
Removing to simplify repository configuration in Terraform HUSH-149.
> HUSH-422 github: remove matrix configuration

- charts/hush-sensor/Chart.yaml
- charts/hush-sensor/templates/_helpers.tpl
- charts/hush-sensor/values.yaml
- tests/tests/test_kubeconform.py
To make it less like k8s Deployment.
> HUSH-429 hush-sensor: rename `deployment.*` to `hushDeployment.*`

- charts/hush-sensor/templates/_helpers.tpl
- charts/hush-sensor/templates/daemonset.yaml
- charts/hush-sensor/templates/deploymentsecret.yaml
- charts/hush-sensor/templates/hushnamespace.yaml
- charts/hush-sensor/templates/imagepullsecret.yaml
- charts/hush-sensor/templates/sensorconfigmap.yaml
- charts/hush-sensor/values.yaml
When a chart creates its Namespace it is impossible to put the Release
object in the same namespace, becauce the namespace doesn't exist yet.
This is a downside because having everything related to some release in
the same namespace makes sense and is probably expected.
Stop creating the Namespace object. Use a pre-created namespace specified
by helm (.Release.Namespace). Allow to override the release namespace by
setting `namespaceOverride` value.
On command line the namespace can be specified as
`helm install -n <namespace-name> ...`.
UI will be updated [1] to use the helm flag accordingly.
Note that this change is not backward compatible because it requires
`helm uninstall` first, and then `helm install -n ...`.
This closes HUSH-662 as well.
[1] …
> HUSH-724 hush-sensor: do not create Namespace in the chart

- charts/hush-sensor/templates/daemonset.yaml
Snoopy needs to know the k8s namespace it operates in order not to track
its own processes.
So far this was passed as part of snoopy's config.yaml.
We'd like to keep snoopy config as an interface of items that allows the
admin to configure snoopy's functionalities.
The self_k8s_namespace isn't such item, it is k8s internal information.
Instead, we can pass this as an env var at the container spec using the
downward api.
> HUSH-784 hush-sensor: provide snoopy container with SELF_K8S_NAMESPACE env var

- charts/hush-sensor/Chart.yaml
This release includes a backward incompatible change. The helm chart
doesn't create the Namespace anymore. Therefore it is required to `helm
uninstall` existing release first and then install with v0.9.0 as new
release.
> HUSH-724 hush-sensor: bump the version to 0.9.0

- charts/hush-sensor/templates/_helpers.tpl
- charts/hush-sensor/templates/sentryclusterrole.yaml
- charts/hush-sensor/templates/sentryclusterrolebinding.yaml
- charts/hush-sensor/templates/sentrydeployment.yaml
- charts/hush-sensor/templates/sentryserviceaccount.yaml
- charts/hush-sensor/values.yaml
Install everything required for Sentry to discover k8s secrets shared
with containers as volumes/envvars.
Set sentry.enabled=false to skip Sentry installation.
> HUSH-674 Install Sentry

- .github/dependabot.yml
Otherwise Capataz fails the build.
> HUSH-777 github: use fixed linear issue for dependabot updates

- charts/hush-sensor/templates/daemonset.yaml
- charts/hush-sensor/templates/sentrydeployment.yaml
- charts/hush-sensor/values.yaml
`hostDir` defines a directory on host that should be mounted in Hush
daemons. This is used as a semi-persistent cache for identifier files
like agent UUID etc.
> HUSH-1136 hush-sensor: add `hostDir` value

- charts/hush-sensor/values.yaml
Will be enabled back in a separate commit.
> HUSH-1031 hush-sensor: disable vermon by default

- tests/Makefile
This was missed in commit 47fe3a0fe8.
> HUSH-1376 tests: remove `--no-update` option from `poetry lock`

- cli/Makefile
This was missed in commit 47fe3a0fe8.
> HUSH-1376 cli: remove `--no-update` option from `poetry lock`

- charts/hush-sensor/templates/daemonset.yaml
- charts/hush-sensor/templates/sensorconfigmap.yaml
- charts/hush-sensor/templates/sentrydeployment.yaml
- charts/hush-sensor/templates/vermondeployment.yaml
- charts/hush-sensor/values.yaml
1. Add a new value `eventReportingConsole` and corresponding ConfigMap
entry `event_reporting_console`.
2. Map `event_reporting_console` into all vectors' env if value is
non-empty string.
> HUSH-1416 hush-sensor: support configuring EVENT_REPORTING_CONSOLE vector env

- cli/cli/charts.py
The forgotten comma isn't a bug because it yields a single string with
two lines. However, in new ruff versions it yields formatting error [1].
Add the forgotten comma to avoid formatting mismatch.
[1]
1 file would be reformatted, 5 files already formatted
--- cli/charts.py
+++ cli/charts.py
@@ -34,7 +34,7 @@
f"cannot add release annotation: annotations already exist {ants}"
)
with open(chart_path(chart_name), "a", encoding="utf-8") as f:
-        lines = ["annotations:\n" f'  security.hush/release: "{RELEASE}"\n']
+        lines = [f'annotations:\n  security.hush/release: "{RELEASE}"\n']
f.writelines(lines)
f.flush()
bash("git diff")
make[1]: *** [Makefile:25: rufflint] Error 1
> HUSH-777 cli: fix formatting error

- charts/hush-sensor/values.yaml
Revert "HUSH-1031 hush-sensor: disable vermon by default"
This reverts commit 4eca013856e5cb389c27bdc29a7b733b79112271.
> HUSH-1031 hush-sensor: enable vermon

- charts/hush-sensor/templates/_helpers.tpl
- charts/hush-sensor/templates/daemonset.yaml
- charts/hush-sensor/templates/sentrydeployment.yaml
- charts/hush-sensor/templates/vermondeployment.yaml
To be reported in heartbeat events. This will help us better understand
customer deployments and possibly alert on misconfigurations.
The `kube-system` namespace is predefined in k8s clusters, therefore it
is very convenient to use its UID as a stable cluster identifier because:
(a) it is unlikely to be deleted or recreated
(b) Helm provides us the `lookup` function to query Namespace
attributes, so it can be retrieved easily unlike the real Cluster ID
> HUSH-1562 hush-sensor: pass more k8s information into vector env

- charts/hush-sensor/ci/sentry-service-account-annotations-values.yaml
- charts/hush-sensor/templates/sentryserviceaccount.yaml
- charts/hush-sensor/values.yaml
This is needed to allow AWS IRSA integration to get sentry access to AWS Secret Manager.
[1] https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html
> HUSH-1754 Custom annotations for sentry service account

- charts/hush-sensor/templates/sentryclusterrole.yaml
Needed to generate Origin events for env vars mapped from ConfigMaps.
> HUSH-1295 hush-sensor: allow sentry read ConfigMaps

- charts/hush-sensor/templates/sentrydeployment.yaml
This is to notify sentry that required permissions are set to read
ConfigMaps.
Sentry needs this new env var to enable ConfigMaps scanning.
The permissions were set in commit 591f990c4c.
> HUSH-1295 hush-sensor: enable `SENTRY_SCAN_CONFIG_MAPS` feature gate

- charts/hush-sensor/values.yaml
There are deployments where nodes are managed in pools grouped by
taints (e.g. karpenter). In such deployments our default settings allow
hush-sensor to run only on non-pool nodes (those without taints).
Add a catch-all toleration to all pods in the chart.
Add well-known node types (like Fargate and Azure Virtual Nodes) to anti-affinity rules to avoid running on them even though tolerations allow it.
> HUSH-1834 hush-sensor: add a catch-all toleration to all services

- charts/hush-sensor/Chart.yaml
- charts/hush-sensor/templates/_helpers.tpl
- charts/hush-sensor/values.yaml
Add support for storing deployment token next to deployment password
in the same k8s Secret.
> HUSH-1796 hush-sensor: support storing deployment token in k8s Secret

- .github/CODEOWNERS
- .github/dependabot.yml
This attribute was deprecated [1] and is replaced by CODEOWNERS file.
Set codeowners to most frequent contributors to the repository.
[1] https://github.blog/changelog/2025-04-29-dependabot-reviewers-configuration-option-being-replaced-by-code-owners/
> HUSH-2199 github: stop using `reviewers` attribute in dependabot configuration

- charts/hush-sensor/templates/_helpers.tpl
- charts/hush-sensor/templates/connectorclusterrole.yaml
- charts/hush-sensor/templates/connectorclusterrolebinding.yaml
- charts/hush-sensor/templates/connectordeployment.yaml
- charts/hush-sensor/templates/connectorserviceaccount.yaml
- charts/hush-sensor/templates/daemonset.yaml
- charts/hush-sensor/templates/daemonsetclusterrole.yaml
- charts/hush-sensor/templates/daemonsetclusterrolebinding.yaml
- charts/hush-sensor/templates/daemonsetserviceaccount.yaml
- charts/hush-sensor/templates/deploymentsecret.yaml
- charts/hush-sensor/templates/sensorconfigmap.yaml
- charts/hush-sensor/templates/sentrydeployment.yaml
- charts/hush-sensor/templates/vermonclusterrole.yaml
- charts/hush-sensor/templates/vermonclusterrolebinding.yaml
- charts/hush-sensor/templates/vermondeployment.yaml
- tests/common/process.py
- tests/tests/test_kubeconform.py
`lookup` cannot be used in some environments (e.g. `argocd`).
Stop using `lookup`. Consequently, stop parsing deployment 
token in Helm. When user provides a reference to a pre-created 
Secret with deployment token/password we do not see the value.
Hence, as we do not use `lookup` anymore, we cannot parse it.
Generation of configuration items based on deployment token
atoms is responsibility of Pods now.
> HUSH-2108 Stop using `lookup` function

- charts/hush-sensor/values.yaml
Leave it on the DaemonSet only.
The reason for this change is that the catch-all toleration allows pods
to run on all nodes including cordoned ones. Running single-instance
Deployments on cordoned nodes is less preferable.
Initially catch-all toleration was added to all deployments to allow
them run on node pools managed/maintained with taints. However, even in
those cases it is assumed that some nodes are untainted. For the
edge case when all nodes are tainted a User has the ability to customize
the tolerations to her needs.
> HUSH-3001 hush-sensor: remove catch-all toleration from Deployments
